### PR TITLE
[WIP] Feat: use terraform-json package

### LINKED ISSUE #48: Refactor to use terraform-json package
[From what i see](https://github.com/dineshba/tf-summarize/blob/c308ae3a61db8d6e869bdc82729c5e858326d00b/terraformstate/terraform_state.go#L16) this tool reads the terraform's standard output format. To enable future compatibility and simplify the codebase i recommend using the following package provided by hashicorp to read the common json format

https://github.com/hashicorp/terraform-json

What are your views on this?

### PR DESCRIPTION
**Pull request by QuintenBruynseraede**
This PR incorporates https://github.com/hashicorp/terraform-json into tf-summarize, by using all the types defined in terraform-json instead of defining our own.

## Changes
Other changes include:
- Rename `AllOutputChanges` -> `GetAllOutputChanges`, `AllResourceChanges` -> `GetAllResourceChanges`, `ColorPrefixAndSuffixText` -> `GetColorPrefixAndSuffixText`
- Add nil checks on all occurrences of `ResourceChange.Change.Importing` (as terraform-json uses pointers instead of straight values)
- Make variables names a bit more consistent (i.e. all instances of `Plan` are called `plan` etc.)

## Tests performed
- `go build .`
- `go test ./...`
- `./tf-summarize (--tree) *.json` on all json files found here: https://github.com/hashicorp/terraform-json/tree/main/testdata

Closes #48

### CODE REVIEW

**Comment by QuintenBruynseraede** [comment]
Hey @dineshba patiently waiting on your input for this (large) PR :). Lmk if I can do anything

**Comment by dineshba** [comment]
I'll review within 1 or 2 days. Sorry occupied with other things... Thanks again for PR. Looks there are some merge conflicts in the PR

**Comment by dineshba** [comment]
Give me couple of days... I am stuck with personal work and will try to review by this weekend

**Comment by QuintenBruynseraede** [comment]
Take your time! Not in a rush

**Review by dineshba — APPROVED** [review]
Thanks a lot this PR. Changes looks good to me. Really appreciate your efforts.

Let me do one round of testing with this binary and merge it...

(Let me create an issue to add e2e tests in the PR pipeline. So that with PR binary, tests will run and print the summary. That will help PR review time)

**Pull request merged**
